In [351]:
import nltk
#nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

In [352]:
#load the data
#data=gutenberg.raw('shakespeare-hamlet.txt')
#saveto file 
#with open('hamlet.txt','w') as file:
 #   file.write(data)

### Data PreProcessing

In [353]:
text=[]
with open('hamlet.txt','r',encoding='utf-8') as f:
    while(f.readline()):
        text.append(f.readline())

def full_stop(text):
    return text.replace(".","").replace("?","").lower()

new_input=[]
for i in input_text:
    new_input.append(full_stop(i))

new_input

[' ',
 'p',
 'l',
 'e',
 'a',
 's',
 'e',
 ' ',
 'f',
 'i',
 'n',
 'd',
 ' ',
 'a',
 't',
 't',
 'a',
 'c',
 'h',
 'e',
 'd',
 ' ',
 't',
 'h',
 'e']

In [354]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

#with open('hamlet.txt','r') as file :
   # txt = file.read().lower()
   
#tokenize
tokenizer = Tokenizer()
tokenizer.fit_on_texts([txt])
total_words = len(tokenizer.word_index)+1
total_words


541

In [355]:
tokenizer.word_index

{"n'": 1,
 'to': 2,
 'the': 3,
 "'i": 4,
 'your': 5,
 'on': 6,
 'for': 7,
 'project': 8,
 'you': 9,
 'in': 10,
 'our': 11,
 'am': 12,
 'that': 13,
 "'your": 14,
 'of': 15,
 'a': 16,
 'should': 17,
 'my': 18,
 "'they": 19,
 'have': 20,
 "'we": 21,
 'recent': 22,
 'is': 23,
 'would': 24,
 'may': 25,
 "'you": 26,
 'confident': 27,
 'find': 28,
 'wanted': 29,
 'appreciate': 30,
 'changes': 31,
 'team': 32,
 'and': 33,
 'positive': 34,
 'we': 35,
 'collaboration': 36,
 "'could": 37,
 'can': 38,
 'upcoming': 39,
 'tasks': 40,
 'need': 41,
 'please': 42,
 'express': 43,
 'impact': 44,
 'might': 45,
 'success': 46,
 "'please": 47,
 'any': 48,
 'it': 49,
 'attention': 50,
 'their': 51,
 'gratitude': 52,
 'n': 53,
 'proposed': 54,
 'successfully': 55,
 'implemented': 56,
 'prioritize': 57,
 'based': 58,
 'review': 59,
 'like': 60,
 'new': 61,
 'potential': 62,
 'writing': 63,
 'address': 64,
 'with': 65,
 'extend': 66,
 'provide': 67,
 'meeting': 68,
 'ability': 69,
 'efficiency': 70,
 'goals': 

In [356]:
## create input sequences
input_sequences =[] 
for line in txt.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [357]:
input_sequences

[[83, 9],
 [83, 9, 7],
 [83, 9, 7, 5],
 [83, 9, 7, 5, 125],
 [83, 9, 7, 5, 125, 293],
 [83, 9, 7, 5, 125, 293, 1],
 [47, 28],
 [47, 28, 78],
 [47, 28, 78, 3],
 [47, 28, 78, 3, 151],
 [47, 28, 78, 3, 151, 9],
 [47, 28, 78, 3, 151, 9, 374],
 [47, 28, 78, 3, 151, 9, 374, 1],
 [14, 50],
 [14, 50, 2],
 [14, 50, 2, 114],
 [14, 50, 2, 114, 23],
 [14, 50, 2, 114, 23, 72],
 [14, 50, 2, 114, 23, 72, 90],
 [14, 50, 2, 114, 23, 72, 90, 1],
 [197, 230],
 [197, 230, 16],
 [197, 230, 16, 167],
 [197, 230, 16, 167, 68],
 [197, 230, 16, 167, 68, 9],
 [197, 230, 16, 167, 68, 9, 252],
 [197, 230, 16, 167, 68, 9, 252, 3],
 [197, 230, 16, 167, 68, 9, 252, 3, 198],
 [197, 230, 16, 167, 68, 9, 252, 3, 198, 1],
 [4, 29],
 [4, 29, 2],
 [4, 29, 2, 43],
 [4, 29, 2, 43, 18],
 [4, 29, 2, 43, 18, 52],
 [4, 29, 2, 43, 18, 52, 7],
 [4, 29, 2, 43, 18, 52, 7, 5],
 [4, 29, 2, 43, 18, 52, 7, 5, 126],
 [4, 29, 2, 43, 18, 52, 7, 5, 126, 1],
 [14, 73],
 [14, 73, 20],
 [14, 73, 20, 95],
 [14, 73, 20, 95, 375],
 [14, 73, 20, 

In [358]:
## Pad Sequences
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

17

In [359]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[  0,   0,   0, ...,   0,  83,   9],
       [  0,   0,   0, ...,  83,   9,   7],
       [  0,   0,   0, ...,   9,   7,   5],
       ...,
       [  0,   0,   0, ..., 537, 538, 539],
       [  0,   0,   0, ..., 538, 539, 540],
       [  0,   0,   0, ..., 539, 540,   1]])

In [360]:
## create predictions and labels 
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]
x.shape
y.shape

(5299,)

In [361]:
x

array([[  0,   0,   0, ...,   0,   0,  83],
       [  0,   0,   0, ...,   0,  83,   9],
       [  0,   0,   0, ...,  83,   9,   7],
       ...,
       [  0,   0,   0, ...,   0, 537, 538],
       [  0,   0,   0, ..., 537, 538, 539],
       [  0,   0,   0, ..., 538, 539, 540]])

In [362]:
y

array([  9,   7,   5, ..., 539, 540,   1])

In [363]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [364]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.2)


In [365]:
#early stopping definition
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [366]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Input, GRU
# Define the model
# model = Sequential()
# model.add(Input(shape=(max_sequence_len - 1,)))
# model.add(Embedding(total_words,100,input_length=max_sequence_len))  # Remove input_length
# model.add(LSTM(150, return_sequences=True))
# model.add(Dropout(0.2))
# model.add(LSTM(100))
# model.add(Dense(total_words, activation="softmax"))

# Compile the model
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Model summary
# model.summary()

### GRU RNN

In [367]:
## Define the model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dropout, Dense, Bidirectional, BatchNormalization, Input

# Define the model
model = Sequential()
model.add(Input(shape=(max_sequence_len - 1,)))
model.add(Embedding(total_words, 128))  # Experiment with different embedding dimensions
model.add(Bidirectional(GRU(150, return_sequences=True)))
model.add(Dropout(0.3))  # Experiment with different dropout rates
model.add(BatchNormalization())
model.add(Bidirectional(GRU(100)))
model.add(Dense(total_words, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Summarize the model
model.summary()


Model: "sequential_36"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_34 (Embedding)        │ (None, 16, 128)        │        69,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 16, 300)        │       252,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_34 (Dropout)            │ (None, 16, 300)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16, 300)        │         1,200 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_3 (Bidirectional) │ (None, 200)            │       241,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 541)            │       108,741 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 672,389 (2.56 MB)

 Trainable params: 671,789 (2.56 MB)

 Non-trainable params: 600 (2.34 KB)

In [368]:
history=model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])


Epoch 1/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step - accuracy: 0.0769 - loss: 5.8164 - val_accuracy: 0.0719 - val_loss: 6.0321
Epoch 2/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.1408 - loss: 4.5565 - val_accuracy: 0.1774 - val_loss: 5.8364
Epoch 3/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.2458 - loss: 3.7565 - val_accuracy: 0.2429 - val_loss: 5.6452
Epoch 4/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.4116 - loss: 2.9882 - val_accuracy: 0.3017 - val_loss: 5.3728
Epoch 5/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.4848 - loss: 2.5925 - val_accuracy: 0.3479 - val_loss: 5.0657
Epoch 6/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.5651 - loss: 2.1175 - val_accuracy: 0.3354 - val_loss: 4.8120
Epoch 7/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.6603 - loss: 1.7207 - val_accuracy: 0.3267 - val_loss: 4.5974
Epoch 8/50
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.7029 - loss: 1.4173 - val_accuracy: 0.3231 - v

In [369]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [370]:
input_text="Please find attached the"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:Please find attached the
Next Word PRediction:document


In [371]:
## Save the model
model.save("next_word_lstm.h5")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [372]:
input_text=" Please find attached the"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word Prediction:{next_word}")

Input text: Please find attached the
Next Word Prediction:document
